name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_HUB_USERNAME }}/terryt-lookup-api_web-api
            ghcr.io/${{ github.actor }}/terryt-lookup-api_web-api

  push-docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./TerrytLookup.WebAPI/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  push-ghcr:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./TerrytLookup.WebAPI/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/terryt-lookup-api_web-api
